Clean up WRSCompositor to be integrated into helix-cockpit
- Remove all of GDP apps
- Add the option to enable/disable to composite aap/carplay surface (default: disable)
- Delete unnecessary directory / icon
- Add the option to set application model

Signed-off-by: Vincent Jeong <vincent.jeong@windriver.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6,54 +6,67 @@
 # Wind River license agreement.
 
 SUPPOTED_TARGETDEVICES=( x11 minnowmax mrb)
-SUPPOTED_HMIPROFILES=( classic cockpit)
+SUPPOTED_HMIPROFILES=( cockpit)
+SUPPORTED_APPSMODEL=( genivi native)
 DUDUREGIPRO=compositor/compositor.pro
 
 show_help() {
-echo "Usage: configure [options]"
-echo "Options: [defaults in brackets after descriptions]"
-echo
-echo "Standard options:"
-echo "  --help                      print this message"
-echo "  --prefix=DIR                prefix dir for installation"
-echo "  --with-digitalcluster       build with digital cluster feature (on 2nd display)"
-echo "  --with-reardisplay          build with rear display feature (on 3rd display)"
-echo "  --without-maindisplay       build without main display"
-echo "  --enable-webengine          Use WebEngine instead of WebKit for WebRuntime"
-echo "  --enable-vthandler          Use VT Handler to switch Virtual Terminal"
-echo "  --enable-virtualkeyboard    Use VirtualKebyaord to send key-value to application"
-echo "  --target-device=NAME        Set JS configuration for specific target device"
-echo "  --hmi-profile=NAME          Set HMI Profile"
-echo "  --overwrite                 overwrite existing config.js by new target/hmi config"
-echo "  --without-qmake             don't execute qmake in configure"
-echo "  --with-qmake=path           set qmake path (e.g - /usr/bin/qmake)"
-echo ""
-echo "Supported target devices:"
-for name in "${SUPPOTED_TARGETDEVICES[@]}"
-do
-	if [ "$name" = "x11" ]; then
-		echo "  $name (default for PC dev environment)"
-	else
-		echo "  $name"
-	fi
-done
-echo ""
-echo "Supported HMI profile:"
-for name in "${SUPPOTED_HMIPROFILES[@]}"
-do
-	if [ "$name" = "classic" ]; then
-		echo "  $name (default for demo)"
-	else
-		echo "  $name"
-	fi
-done
-echo
+    echo "Usage: configure [options]"
+    echo "Options: [defaults in brackets after descriptions]"
+    echo
+    echo "Standard options:"
+    echo "  --help                      print this message"
+    echo "  --prefix=DIR                prefix dir for installation"
+    echo "  --with-digitalcluster       build with digital cluster feature (on 2nd display)"
+    echo "  --with-reardisplay          build with rear display feature (on 3rd display)"
+    echo "  --without-maindisplay       build without main display"
+    echo "  --enable-webengine          Use WebEngine instead of WebKit for WebRuntime"
+    echo "  --enable-vthandler          Use VT Handler to switch Virtual Terminal"
+    echo "  --enable-virtualkeyboard    Use VirtualKebyaord to send key code to application"
+    echo "  --enable-projection         Use Connectivity Projection related to CarPlay/Aap"
+    echo "  --apps-model=NAME           Set application model"
+    echo "  --target-device=NAME        Set JS configuration for specific target device"
+    echo "  --hmi-profile=NAME          Set HMI Profile"
+    echo "  --overwrite                 overwrite existing config.js by new target/hmi config"
+    echo "  --without-qmake             don't execute qmake in configure"
+    echo "  --with-qmake=path           set qmake path (e.g - /usr/bin/qmake)"
+    echo ""
+    echo "Supported target devices:"
+    for name in "${SUPPOTED_TARGETDEVICES[@]}"
+    do
+        if [ "$name" = "x11" ]; then
+            echo "  $name (default for PC dev environment)"
+        else
+            echo "  $name"
+        fi
+    done
+    echo ""
+    echo "Supported HMI profile:"
+    for name in "${SUPPOTED_HMIPROFILES[@]}"
+    do
+        if [ "$name" = "cockpit" ]; then
+            echo "  $name (default for demo)"
+        else
+            echo "  $name"
+        fi
+    done
+    echo ""
+    echo "Supported Apps Model:"
+    for name in "${SUPPORTED_APPSMODEL[@]}"
+    do
+        if [ "$name" = "genivi" ]; then
+            echo "  $name (default for demo)"
+        else
+            echo "  $name"
+        fi
+    done
+    echo
 }
 
 if [ "$1" = -h -o "$1" = -help -o "$1" = --help ]
 then
     show_help
-	exit
+    exit
 fi
 
 SUPPORT_MAINDISPLAY=1
@@ -63,10 +76,12 @@ SUPPORT_WLCOMPOSITOR=1
 SUPPORT_WEBENGINE=0
 SUPPORT_VTHANDLER=0
 SUPPORT_VIRTUAL_KEYBOARD=0
+SUPPORT_CONNECTIVITY_PROJECTION=0
 SUPPORT_DBUS=1
 MANUAL_QMAKE=0
 TARGET_DEVICE=x11
-HMI_PROFILE=classic
+APPS_MODEL=native
+HMI_PROFILE=cockpit
 OVERWRITE=0
 QMAKEPATH=
 OPTARGS=""
@@ -75,99 +90,117 @@ PREFIX=/usr
 for opt do
     optval="${opt#*=}"
     case "$opt" in
-    --without-maindisplay)
-		SUPPORT_MAINDISPLAY=0
-	;;
-    --enable-webengine)
-		SUPPORT_WEBENGINE=1
-	;;
-    --enable-vthandler)
-		SUPPORT_VTHANDLER=1
-	;;
-    --enable-virtualkeyboard)
-		SUPPORT_VIRTUAL_KEYBOARD=1
-	;;
-    --with-digitalcluster)
-		SUPPORT_DCLUSTER=1
-	;;
-    --with-reardisplay)
-		SUPPORT_REARDISPLAY=1
-	;;
-    --without-qmake)
-		MANUAL_QMAKE=1
-	;;
-    --with-qmake=*)
-		if [ ! -f "$optval" ]; then
-			echo "Error, Could not found $optval"
-			exit 1
-		fi
-		QMAKEPATH=$optval
-	;;
-    --prefix=*)
-		PREFIX=$optval
-	;;
-    --target-device=*)
-		for name in "${SUPPOTED_TARGETDEVICES[@]}"
-		do
-			if [ $name = $optval ]; then
-                TARGET_DEVICE=$optval
-				break
-			fi
-		done
-		if [ $optval != $TARGET_DEVICE ]; then
-			show_help
-			echo
-			echo "\"$optval\" is not supported target device"
-			exit
-		fi
-	;;
-    --hmi-profile=*)
-		for name in "${SUPPOTED_HMIPROFILES[@]}"
-		do
-			if [ $name = $optval ]; then
-                HMI_PROFILE=$optval
-				break
-			fi
-		done
-		if [ $optval != $HMI_PROFILE ]; then
-			show_help
-			echo
-			echo "\"$optval\" is not supported HMI Profile"
-			exit
-		fi
-	;;
-    --overwrite)
-		OVERWRITE=1
-	;;
-    --help)
-	show_help
-	exit
-	;;
-	*)
-		OPTARGS="$opt $OPTARGS"
-	;;
+        --without-maindisplay)
+            SUPPORT_MAINDISPLAY=0
+            ;;
+        --enable-webengine)
+            SUPPORT_WEBENGINE=1
+            ;;
+        --enable-vthandler)
+            SUPPORT_VTHANDLER=1
+            ;;
+        --enable-virtualkeyboard)
+            SUPPORT_VIRTUAL_KEYBOARD=1
+            ;;
+        --enable-projection)
+            SUPPORT_CONNECTIVITY_PROJECTION=1
+            ;;
+        --with-digitalcluster)
+            SUPPORT_DCLUSTER=1
+            ;;
+        --with-reardisplay)
+            SUPPORT_REARDISPLAY=1
+            ;;
+        --without-qmake)
+            MANUAL_QMAKE=1
+            ;;
+        --with-qmake=*)
+            if [ ! -f "$optval" ]; then
+                echo "Error, Could not found $optval"
+                exit 1
+            fi
+            QMAKEPATH=$optval
+            ;;
+        --prefix=*)
+            PREFIX=$optval
+            ;;
+        --target-device=*)
+            for name in "${SUPPOTED_TARGETDEVICES[@]}"
+            do
+                if [ $name = $optval ]; then
+                    TARGET_DEVICE=$optval
+                    break
+                fi
+            done
+            if [ $optval != $TARGET_DEVICE ]; then
+                show_help
+                echo
+                echo "\"$optval\" is not supported target device"
+                exit
+            fi
+            ;;
+        --hmi-profile=*)
+            for name in "${SUPPOTED_HMIPROFILES[@]}"
+            do
+                if [ $name = $optval ]; then
+                    HMI_PROFILE=$optval
+                    break
+                fi
+            done
+            if [ $optval != $HMI_PROFILE ]; then
+                show_help
+                echo
+                echo "\"$optval\" is not supported HMI Profile"
+                exit
+            fi
+            ;;
+        --apps-model=*)
+            for name in "${SUPPORTED_APPSMODEL[@]}"
+            do
+                if [ $name = $optval ]; then
+                    APPS_MODEL=$optval
+                    break
+                fi
+            done
+            if [ $optval != $APPS_MODEL ]; then
+                show_help
+                echo
+                echo "\"$optval\" is not supported Apps model"
+                exit
+            fi
+            ;;
+        --overwrite)
+            OVERWRITE=1
+            ;;
+        --help)
+            show_help
+            exit
+            ;;
+        *)
+            OPTARGS="$opt $OPTARGS"
+            ;;
     esac
 done
 
 
 
 if [ "$QMAKEPATH" = "" ]; then
-QMAKEPATH_IN_LINUXDISTROS=( /usr/bin /usr/bin/qt5)
-FOUND=0
-for bindir in "${QMAKEPATH_IN_LINUXDISTROS[@]}"
-do
-	if [ -f $bindir/qmake ]; then
-		QMAKEPATH=$bindir/qmake
-		break
-	elif [ -f $bindir/qmake-qt5 ]; then
-		QMAKEPATH=$bindir/qmake-qt5
-		break
-	fi
-done
+    QMAKEPATH_IN_LINUXDISTROS=( /usr/bin /usr/bin/qt5)
+    FOUND=0
+    for bindir in "${QMAKEPATH_IN_LINUXDISTROS[@]}"
+    do
+        if [ -f $bindir/qmake ]; then
+            QMAKEPATH=$bindir/qmake
+            break
+        elif [ -f $bindir/qmake-qt5 ]; then
+            QMAKEPATH=$bindir/qmake-qt5
+            break
+        fi
+    done
 fi
 if [ "$QMAKEPATH" = "" ]; then
-	echo "Error, Could not found qmake, please set with --with-qmake"
-	exit 1
+    echo "Error, Could not found qmake, please set with --with-qmake"
+    exit 1
 fi
 export PATH=`dirname $QMAKEPATH`:$PATH
 
@@ -181,6 +214,7 @@ echo "  SUPPORT_VTHANDLER=$SUPPORT_VTHANDLER"
 echo "  SUPPORT_DBUS=$SUPPORT_DBUS"
 echo "  TARGET_DEVICE=$TARGET_DEVICE"
 echo "  HMI_PROFILE=$HMI_PROFILE"
+echo "  APPS_MODEL=$APPS_MODEL"
 echo "  OPTARGS: $OPTARGS"
 echo "  PREFIX: $PREFIX"
 echo
@@ -203,25 +237,25 @@ echo
 
 printf "Checking pkg-config wayland-server ..."
 if ! pkg-config --exists wayland-server ; then
-echo $'\r'"Checking pkg-config wayland-server ........................ Failure"
-echo "Error, Please install wayland development package(s)"
-echo "   ubuntu: libwayland-dev"
-echo "   fedora: wayland-devel, libwayland-server-devel"
-echo "           libwayland-client-devel, libwayland-cursor-devel"
-exit 1
+    echo $'\r'"Checking pkg-config wayland-server ........................ Failure"
+    echo "Error, Please install wayland development package(s)"
+    echo "   ubuntu: libwayland-dev"
+    echo "   fedora: wayland-devel, libwayland-server-devel"
+    echo "           libwayland-client-devel, libwayland-cursor-devel"
+    exit 1
 else
-echo $'\r'"Checking pkg-config wayland-server ........................... Done"
+    echo $'\r'"Checking pkg-config wayland-server ........................... Done"
 fi
 
 printf "Checking pkg-config gbm ..."
 if ! pkg-config --exists gbm ; then
-echo $'\r'"Checking pkg-config gbm ................................... Failure"
-echo "Error, Please install gbm development package(s)"
-echo "   ubuntu: libgbm-dev"
-echo "   fedora: mesa-libgbm-devel"
-exit 1
+    echo $'\r'"Checking pkg-config gbm ................................... Failure"
+    echo "Error, Please install gbm development package(s)"
+    echo "   ubuntu: libgbm-dev"
+    echo "   fedora: mesa-libgbm-devel"
+    exit 1
 else
-echo $'\r'"Checking pkg-config gbm ...................................... Done"
+    echo $'\r'"Checking pkg-config gbm ...................................... Done"
 fi
 
 #printf "Checking pkg-config libsystemd-login ..."
@@ -240,44 +274,44 @@ printf "Generating compositor.pro ..."
 echo "QT += quick qml network gui-private"  > $DUDUREGIPRO
 
 if [ "$SUPPORT_WEBENGINE" = "1" ]; then
-echo "QT += webengine" >> $DUDUREGIPRO
+    echo "QT += webengine" >> $DUDUREGIPRO
 else
-echo "QT += webkitwidgets" >> $DUDUREGIPRO
+    echo "QT += webkitwidgets" >> $DUDUREGIPRO
 fi
 
 if [ "$SUPPORT_WLCOMPOSITOR" = "1" ]; then
-echo "DEFINES += QT_COMPOSITOR_QUICK" >> $DUDUREGIPRO
-echo "QT += compositor" >> $DUDUREGIPRO
+    echo "DEFINES += QT_COMPOSITOR_QUICK" >> $DUDUREGIPRO
+    echo "QT += compositor" >> $DUDUREGIPRO
 
-echo "QT += compositor-private" >> $DUDUREGIPRO
-echo "CONFIG +=wayland-scanner" >> $DUDUREGIPRO
-echo "WAYLANDSERVERSOURCES += protocols/ivi-controller.xml" >> $DUDUREGIPRO
-echo "WAYLANDSERVERSOURCES += protocols/ivi-application.xml" >> $DUDUREGIPRO
-echo "CONFIG += link_pkgconfig" >> $DUDUREGIPRO
-echo "PKGCONFIG += wayland-server gbm" >> $DUDUREGIPRO
-echo "HEADERS += GeniviWaylandIVIExtension.h" >> $DUDUREGIPRO
-echo "SOURCES += GeniviWaylandIVIExtension.cpp" >> $DUDUREGIPRO
+    echo "QT += compositor-private" >> $DUDUREGIPRO
+    echo "CONFIG +=wayland-scanner" >> $DUDUREGIPRO
+    echo "WAYLANDSERVERSOURCES += protocols/ivi-controller.xml" >> $DUDUREGIPRO
+    echo "WAYLANDSERVERSOURCES += protocols/ivi-application.xml" >> $DUDUREGIPRO
+    echo "CONFIG += link_pkgconfig" >> $DUDUREGIPRO
+    echo "PKGCONFIG += wayland-server gbm" >> $DUDUREGIPRO
+    echo "HEADERS += GeniviWaylandIVIExtension.h" >> $DUDUREGIPRO
+    echo "SOURCES += GeniviWaylandIVIExtension.cpp" >> $DUDUREGIPRO
 
 fi
 
 if [ "$HMI_PROFILE" = "cockpit" ]; then
-echo "HEADERS += virtualkeyboard.h" >> $DUDUREGIPRO
-echo "SOURCES += virtualkeyboard.cpp" >> $DUDUREGIPRO
+    echo "HEADERS += virtualkeyboard.h" >> $DUDUREGIPRO
+    echo "SOURCES += virtualkeyboard.cpp" >> $DUDUREGIPRO
 fi
 
 if [ "$SUPPORT_DCLUSTER" = "1" ]; then
-echo "HEADERS += digitalcluster.h" >> $DUDUREGIPRO
-echo "SOURCES += digitalcluster.cpp" >> $DUDUREGIPRO
+    echo "HEADERS += digitalcluster.h" >> $DUDUREGIPRO
+    echo "SOURCES += digitalcluster.cpp" >> $DUDUREGIPRO
 fi
 
 if [ "$SUPPORT_REARDISPLAY" = "1" ]; then
-echo "HEADERS += reardisplay.h" >> $DUDUREGIPRO
-echo "SOURCES += reardisplay.cpp" >> $DUDUREGIPRO
-echo "OTHER_FILES += rearmain.qml" >> $DUDUREGIPRO
+    echo "HEADERS += reardisplay.h" >> $DUDUREGIPRO
+    echo "SOURCES += reardisplay.cpp" >> $DUDUREGIPRO
+    echo "OTHER_FILES += rearmain.qml" >> $DUDUREGIPRO
 fi
 
 if [ "$SUPPORT_DBUS" = "1" ]; then
-echo "QT += dbus" >> $DUDUREGIPRO
+    echo "QT += dbus" >> $DUDUREGIPRO
 fi
 echo "QT += multimedia" >> $DUDUREGIPRO
 
@@ -292,50 +326,55 @@ echo $'\r'"Generating compositor.pro .................................... Done"
 
 printf "Generating duduregiconfig.h ..."
 cat compositor/duduregiconfig.h.in | sed \
--e "s/DUDUREGI_MAINDISPLAY 0/DUDUREGI_MAINDISPLAY $SUPPORT_MAINDISPLAY/" \
--e "s/DUDUREGI_DIGITALCLUSTER 0/DUDUREGI_DIGITALCLUSTER $SUPPORT_DCLUSTER/" \
--e "s/DUDUREGI_REARDISPLAY 0/DUDUREGI_REARDISPLAY $SUPPORT_REARDISPLAY/" \
--e "s/DUDUREGI_WAYLAND_COMPOSITOR 0/DUDUREGI_WAYLAND_COMPOSITOR $SUPPORT_WLCOMPOSITOR/" \
--e "s/DUDUREGI_WEBENGINE 0/DUDUREGI_WEBENGINE $SUPPORT_WEBENGINE/" \
--e "s/DUDUREGI_VTHANDLER 0/DUDUREGI_VTHANDLER $SUPPORT_VTHANDLER/" \
--e "s/DUDUREGI_VIRTUAL_KEYBOARD 0/DUDUREGI_VIRTUAL_KEYBOARD $SUPPORT_VIRTUAL_KEYBOARD/" \
--e "s/DUDUREGI_DBUS 0/DUDUREGI_DBUS $SUPPORT_DBUS/" \
--e "s/DEFAULT_TARGET_DEVICE/$TARGET_DEVICE/" \
--e "s/DEFAULT_HMI_PROFILE/$HMI_PROFILE/" \
-> compositor/duduregiconfig.h
+    -e "s/DUDUREGI_MAINDISPLAY 0/DUDUREGI_MAINDISPLAY $SUPPORT_MAINDISPLAY/" \
+    -e "s/DUDUREGI_DIGITALCLUSTER 0/DUDUREGI_DIGITALCLUSTER $SUPPORT_DCLUSTER/" \
+    -e "s/DUDUREGI_REARDISPLAY 0/DUDUREGI_REARDISPLAY $SUPPORT_REARDISPLAY/" \
+    -e "s/DUDUREGI_WAYLAND_COMPOSITOR 0/DUDUREGI_WAYLAND_COMPOSITOR $SUPPORT_WLCOMPOSITOR/" \
+    -e "s/DUDUREGI_WEBENGINE 0/DUDUREGI_WEBENGINE $SUPPORT_WEBENGINE/" \
+    -e "s/DUDUREGI_VTHANDLER 0/DUDUREGI_VTHANDLER $SUPPORT_VTHANDLER/" \
+    -e "s/DUDUREGI_VIRTUAL_KEYBOARD 0/DUDUREGI_VIRTUAL_KEYBOARD $SUPPORT_VIRTUAL_KEYBOARD/" \
+    -e "s/DUDUREGI_DBUS 0/DUDUREGI_DBUS $SUPPORT_DBUS/" \
+    -e "s/DEFAULT_TARGET_DEVICE/$TARGET_DEVICE/" \
+    -e "s/DEFAULT_HMI_PROFILE/$HMI_PROFILE/" \
+    > compositor/duduregiconfig.h
 echo $'\r'"Generating duduregiconfig.h .................................. Done"
 
 printf "Generating config.js for hmi profile ..."
 TARGETDIR="compositor/targets/$TARGET_DEVICE"
 CONFIGJS=compositor/hmi/$HMI_PROFILE/config.js
 if [ -d "$TARGETDIR" ]; then
-	OVERWRITTEN=0
-	if [ -f $CONFIGJS ]; then
-echo $'\r'"Generating config.js for hmi profile ............... Already Exists"
-		if [ "$OVERWRITE" = "0" ]; then
-			echo "Error, Could not write $CONFIGJS, It's alreay exists"
-			echo "Use --overwrite or remove it first before do configure"
-			exit 1
-		fi
-		OVERWRITTEN=1
-	fi
-	cp -f compositor/config-default.js $CONFIGJS
-	if [ -f "$TARGETDIR/config-opt.js" ]; then
-		cat $TARGETDIR/config-opt.js >> $CONFIGJS
-	fi
-	if [ "$SUPPORT_WEBENGINE" = "1" ]; then
-		echo "useWebEngine = $SUPPORT_WEBENGINE;" >> $CONFIGJS
-	fi
-
-	if [ "$OVERWRITTEN" = "1" ]; then
-echo $'\r'"                    overwritten at $CONFIGJS"
-	else
-echo $'\r'"Generating config.js for hmi profile ......................... Done"
-	fi
+    OVERWRITTEN=0
+    if [ -f $CONFIGJS ]; then
+        echo $'\r'"Generating config.js for hmi profile ............... Already Exists"
+        if [ "$OVERWRITE" = "0" ]; then
+            echo "Error, Could not write $CONFIGJS, It's alreay exists"
+            echo "Use --overwrite or remove it first before do configure"
+            exit 1
+        fi
+        OVERWRITTEN=1
+    fi
+    cp -f compositor/config-default.js $CONFIGJS
+    if [ -f "$TARGETDIR/config-opt.js" ]; then
+        cat $TARGETDIR/config-opt.js >> $CONFIGJS
+    fi
+    if [ "$SUPPORT_WEBENGINE" = "1" ]; then
+        echo "useWebEngine = $SUPPORT_WEBENGINE;" >> $CONFIGJS
+    fi
+    if [ "$SUPPORT_CONNECTIVITY_PROJECTION" = "1" ]; then
+        echo "useConnectivityProjectionFeature = $SUPPORT_CONNECTIVITY_PROJECTION;" >> $CONFIGJS
+    fi
+    if [ "$APPS_MODEL" = "genivi" ]; then
+        echo "appsModel = '$APPS_MODEL';" >> $CONFIGJS
+    fi
+    if [ "$OVERWRITTEN" = "1" ]; then
+        echo $'\r'"                    overwritten at $CONFIGJS"
+    else
+        echo $'\r'"Generating config.js for hmi profile ......................... Done"
+    fi
 else
-echo $'\r'"Generating config.js for hmi profile ...................... Failure"
-echo "Error, not supported target device: $TARGET_DEVICE"
-exit
+    echo $'\r'"Generating config.js for hmi profile ...................... Failure"
+    echo "Error, not supported target device: $TARGET_DEVICE"
+    exit
 fi
 echo
 
@@ -347,7 +386,7 @@ echo "<RCC>" > $RCPATH
 echo "  <qresource prefix=\"/\">" >> $RCPATH
 for name in `find . -name '*.qml' -o -name '*.js' -o -name '*.jpg' -o -name '*.png' -o -name '*.svg' -o -name '*.otf' | sed -e "s/.\///"`
 do
-	echo "    <file alias=\"$name\">hmi/$HMI_PROFILE/$name</file>" >> $RCPATH
+    echo "    <file alias=\"$name\">hmi/$HMI_PROFILE/$name</file>" >> $RCPATH
 done
 echo "  </qresource>" >> $RCPATH
 echo "</RCC>" >> $RCPATH
@@ -362,9 +401,9 @@ cat vt-handler/vt-handler.pro.in >> vt-handler/vt-handler.pro
 echo $'\r'"Generating vt-handler.pro .................................... Done"
 
 if [ "$MANUAL_QMAKE" = "0" ]; then
-	$QMAKEPATH $OPTARGS && echo "Makefile generated"
+    $QMAKEPATH $OPTARGS && echo "Makefile generated"
 else
-	echo "Please execute qmake to create a Makefile"
+    echo "Please execute qmake to create a Makefile"
 fi
 echo "Configuration Completed"
 echo $0 $@ > config.log
